In [2]:
import pandas as pd
import numpy as np
boards = pd.read_csv('data/advent4.csv', header=None)[0].str.strip().str.split(' +', expand=True).to_numpy()
numbers = [72,99,88,8,59,61,96,92,2,70,1,32,18,10,95,33,20,31,66,43,26,24,91,44,11,15,48,90,27,29,14,68,3,50,69,74,54,4,16,55,64,12,73,80,58,83,6,87,30,41,25,39,93,60,9,81,63,75,46,19,78,51,21,28,94,7,17,42,53,13,97,98,34,76,89,23,86,52,79,85,67,84,47,22,37,65,71,49,82,40,77,36,62,0,56,45,57,38,35,5]
num_boards = int(boards.shape[0] / boards.shape[1])  # Assuming boards are square

matches = np.vsplit(np.full(boards.shape, False, dtype=bool), num_boards)
boards = np.vsplit(boards.astype(int), num_boards)

def check_bingo(board):
    return np.any(np.all(board, axis=0)) or np.any(np.all(board, axis=1)) or np.all(np.diag(board)) or np.all(np.diag(np.rot90(board)))

active_boards = set(range(num_boards))

for number in numbers:
    for i in range(num_boards):
        board = boards[i]
        matches[i] = np.logical_or(board == number, matches[i])
        if check_bingo(matches[i]):
            try: active_boards.remove(i)
            except: _

            if len(active_boards) == 1: # Set to 99 for part 1 of the question, 1 for part 2 of the question
                print(number)
                print(board)
                print((1 - matches[i]) * board) # The still-active squares
                print(np.sum((1 - matches[i]) * board) * number) # The answer
                raise ValueError # double break



22
[[70 57 62 20 18]
 [86 45 41 76 32]
 [87 35 52  5  2]
 [16 77 25 39 22]
 [38 10  6 29 98]]
[[ 0 57 62  0  0]
 [ 0 45  0  0  0]
 [ 0 35  0  5  0]
 [ 0 77  0  0  0]
 [38  0  0  0  0]]
7018


ValueError: 

In [12]:
num_boards

100.0